INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Abatiá',58),
	 (N'Águas Lindas de Goiás',48),
	 (N'Almeirim',17),
	 (N'Almirante Tamandaré',34),
	 (N'Anápolis',15),
	 (N'Apucarana',13),
	 (N'Arapongas',17),
	 (N'Araquari',51),
	 (N'Araraquara',15),
	 (N'Araucária',113);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Assaí',13),
	 (N'Barro Alto',18),
	 (N'Barueri',13010),
	 (N'Bauru',12),
	 (N'Bela Vista do Paraíso',14),
	 (N'Belém',12),
	 (N'Belo Horizonte',96),
	 (N'Betim',13),
	 (N'Bituruna',11),
	 (N'Brasília',1121);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Cambé',82),
	 (N'Camocim de São Félix',13),
	 (N'Campina do Simão',42),
	 (N'Campina Grande do Sul',44),
	 (N'Campinas',40),
	 (N'Campo Grande',546),
	 (N'Campo Largo',14),
	 (N'Campo Limpo Paulista',145),
	 (N'Campo Mourão',14),
	 (N'Campos do Jordão',46);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Campos dos Goytacazes',11),
	 (N'Canoinhas',12),
	 (N'Caraguatatuba',693),
	 (N'Carapicuíba',18),
	 (N'Cardoso',45),
	 (N'Cariacica',39),
	 (N'Cascavel',160),
	 (N'Catanduva',27),
	 (N'Chapecó',12),
	 (N'Cidade Ocidental',23);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Colatina',16),
	 (N'Colombo',250),
	 (N'Condado',48),
	 (N'Contagem',116),
	 (N'Coronel Fabriciano',49),
	 (N'Curitiba',1651),
	 (N'Diadema',13),
	 (N'Esperantina',26),
	 (N'Fazenda Rio Grande',15),
	 (N'Goiana',32);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Goiânia',67),
	 (N'Governador Valadares',816),
	 (N'Gravataí',15),
	 (N'Guarapuava',11),
	 (N'Guaraqueçaba',21),
	 (N'Guarujá',179),
	 (N'Guarulhos',65),
	 (N'Ibiporã',45),
	 (N'Iepê',15),
	 (N'Indaiatuba',533);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Itacoatiara',14),
	 (N'Itapecerica da Serra',42),
	 (N'Itapeva',18),
	 (N'Itapira',681),
	 (N'Itararé',72),
	 (N'Itatiba',127),
	 (N'Ivinhema',14),
	 (N'Jaboatão dos Guararapes',28),
	 (N'Jacareí',41),
	 (N'Jaguariaíva',20);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Jales',245),
	 (N'Jequié',28),
	 (N'João Monlevade',41),
	 (N'Joinville',29),
	 (N'Juazeiro',27),
	 (N'Lapa',11),
	 (N'Lavras',99),
	 (N'Leme',68),
	 (N'Linhares',17),
	 (N'Londrina',1514);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Lorena',21),
	 (N'Luziânia',34),
	 (N'Macaé',12),
	 (N'Mafra',92),
	 (N'Manaus',12),
	 (N'Maracanaú',93),
	 (N'Maranguape',14),
	 (N'Maringá',17),
	 (N'Matinhos',16),
	 (N'Mogi das Cruzes',13);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Niterói',179),
	 (N'Nova Lima',17),
	 (N'Olinda',24),
	 (N'Ortigueira',114),
	 (N'Osasco',45),
	 (N'Ourinhos',15),
	 (N'Ourizona',21),
	 (N'Pacaraima',63),
	 (N'Palhoça',10),
	 (N'Palmas',12);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Paranaguá',219),
	 (N'Paranavaí',117),
	 (N'Parnaíba',18),
	 (N'Pato Branco',78),
	 (N'Patos de Minas',23),
	 (N'Paulínia',217),
	 (N'Paulista',16),
	 (N'Peruíbe',507),
	 (N'Pindamonhangaba',65),
	 (N'Pinhais',69);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Piracicaba',117),
	 (N'Piraquara',351),
	 (N'Pitangueiras',26),
	 (N'Planaltina',21),
	 (N'Planalto',24),
	 (N'Pontal do Paraná',10),
	 (N'Presidente Prudente',53),
	 (N'Recife',1464),
	 (N'Ribeirão Pires',52),
	 (N'Rio Branco',150);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Rio de Janeiro',102),
	 (N'Rio Negro',3246),
	 (N'Rolândia',34),
	 (N'Salvador',38),
	 (N'Santa Adélia',17),
	 (N'Santa Albertina',17),
	 (N'Santa Amélia',16),
	 (N'Santa Fé do Sul',84),
	 (N'Santa Helena',60),
	 (N'Santo André',34);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Santo Antônio do Descoberto',12),
	 (N'Santos',75),
	 (N'São Bernardo do Campo',799),
	 (N'São Caetano do Sul',110),
	 (N'São José do Rio Preto',29767),
	 (N'São José dos Campos',74),
	 (N'São José dos Pinhais',385),
	 (N'São Luís',39),
	 (N'São Paulo',1082),
	 (N'São Pedro',10);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Sarandi',10),
	 (N'Serra',78),
	 (N'Sertanópolis',14),
	 (N'Sete Barras',22),
	 (N'Sorocaba',19),
	 (N'Teixeira de Freitas',11),
	 (N'Teresina',166),
	 (N'Trindade',404),
	 (N'Uberaba',209),
	 (N'Uberlândia',63);
INSERT INTO master.dbo.vw_municipios_com_10_ou_mais_casos (nome_municipio,quantidade_casos) VALUES
	 (N'Valparaíso de Goiás',64),
	 (N'Várzea Paulista',38),
	 (N'Vila Velha',126),
	 (N'Vitória',271);
